addons:
  apt:
    packages:
    - oracle-java8-installer
after_success:
- "if [ \"$TRAVIS_EVENT_TYPE\" != cron ] && [ \"$TRAVIS_REPO_SLUG\" == torodb/stampede\
  \ ]\nthen\n    # Upload reports to Codecov\n    bash <(curl -s https://codecov.io/bash)\
  \ || echo 'Codecov did not collect coverage reports';\n    # Upload reports to Codacy\n\
  \    java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter\
  \ -l Java -r reporting/target/site/jacoco-aggregate/jacoco.xml || echo 'Codacy report\
  \ fail'\nelse\n    echo 'Skipping a metrics reports because this repo/build is not\
  \ permitted'\nfi\n"
before_cache:
- rm -f $HOME/.m2/repository/com/torodb
- rm -rf $HOME/CACHE; find $TRAVIS_BUILD_DIR -name .ekstazi | while read line; do
  du -sh $line;         DIR=$(dirname $HOME/CACHE$line); mkdir -p $DIR; cp -r $line
  $DIR; done
- echo CACHESIZE $(du -sk $HOME/CACHE)
- cp /tmp/classpathFile $HOME/CACHE/classpathFile
before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then sed -i '' 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        else sed -i 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        fi
- find $HOME/CACHE -name .ekstazi | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#.ekstazi/} ]]; then cp -r $line $DIR; fi; done
- wget https://archive.apache.org/dist/maven/maven-3/3.2.2/binaries/apache-maven-3.2.2-bin.tar.gz
- tar xf apache-maven-3.2.2-bin.tar.gz
- export M2_HOME=$PWD/apache-maven-3.2.2
- export PATH=$M2_HOME/bin:$PATH
- sudo apt-get install jq
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest
  | jq -r .assets[0].browser_download_url)
before_script:
- find $TRAVIS_BUILD_DIR -name .ekstazi | while read line; do rm -rf $line; done
- find $HOME/CACHE -name .ekstazi | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#.ekstazi/} ]]; then cp -r $line $DIR; fi; done
- export GIT_BRANCH=$TRAVIS_BRANCH
- if [ "$TRAVIS_OS_NAME" == "osx" ];    then sed -i '' 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;    else sed -i 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;    fi
- if [[ -e $HOME/CACHE/classpathFile ]]; then cp $HOME/CACHE/classpathFile /tmp/;
  fi
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/CACHE
  - $HOME/CACHE
dist: trusty
jdk: oraclejdk8
language: java
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- "if [ \"$TRAVIS_EVENT_TYPE\" == cron ] && [ \"$TRAVIS_BRANCH\" == devel ]\nthen\n\
  \    bash .travis/build-packages\nelse\n    mvn -Psafer -Pintegration -B -e -T 1C\
  \ -Dcheckstyle.consoleOutput=false --update-snapshots verify\nfi\n"
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
sudo: required
